### ISSUE TITLE
Spaces in -fs_userpath are not allowed

### ISSUE THREAD

**Issue by DeathByDenim** [opensoldat/opensoldat#122]
When trying to set `-fs_userpath` to a path with spaces, only the part before the space is being considered. For example, when running opensoldat like this:
```
./bin/opensoldat -fs_portable 0 -fs_userpath ~/temp/soldat\ with\ space -join 127.0.0.1 23073
```
The reason is that at some point in shared/Command.pas there is code like this;
```
  InputParse := TStringList.Create;
  InputParse.Delimiter := ' ';
  InputParse.DelimitedText := TrimLeft(Input);
```
So even though the argument is correctly supplied on the command line, the above code will just split it out anyway.

I'll open a PR for this one. I was able to solve this one locally (although it's affected by issue #121).

**Comment by BranDougherty** [comment]
It's actually possible to do this already, quoted strings are supported out of the box by `TStringList`. You can see it in action in the default `server.cfg`, where `sv_hostname` is set to "My Server" (with the space included). Using this from the command line will probably be ugly, because the quote needs to actually reach OpenSoldat and shells like to mess with quotes. The following worked ok for me with bash and fish:
```bash
./opensoldatserver -fs_userpath "\"~/temp/soldat with space\"" -log_level 1
```

But of course this is a pretty bad documentation problem, which should be solved ASAP. Anyone is welcome to take a stab at adding a few pages to the wiki, and I'll try to get around to adding some documentation myself soon.

**Comment by DeathByDenim** [comment]
Oh, I see. I didn't think of trying that!

It's not exactly pretty though. That gave me an idea. The same could be achieved by changing [shared/Command.pas:491](https://github.com/opensoldat/opensoldat/blob/develop/shared/Command.pas#L491) from this:
```
      CurrentCommand := CurrentCommand + ' ' + argv[i];
```
to this:
```
      CurrentCommand := CurrentCommand + ' "' + argv[i] + '"';
```

I just tried that out and it this allows me tu run as:
```
./bin/opensoldat -fs_portable 0 -fs_userpath ~/temp/soldat\ with\ space -join 127.0.0.1 23073 -log_level 1
```
Now escaped spaces work as expected and all the other command-line arguments remain functional as well. What do you think of doing it like that? You wouldn't have to rely on people reading documentation.

**Comment by BranDougherty** [comment]
Wayyy better thanks.
