### ISSUE TITLE
Weird cvars issues

### ISSUE THREAD

**Issue by Dankage102** [opensoldat/opensoldat#143]
sv_anticheatkick (1.7.1 has Disable_AntiCheat_Kick)
sv_minimap (1.7.1 has Disable_Minimap)
sv_sniperline (1.7.1 has NoSniperLine)
As You see 1.7.1 has very weird counterintuitive names for those options...

The names has changed but the values work the same as in 1.7.1 i.e. setting `sv_minimap "0"` enables the minimap

I've set sv_gravity to 0.06(default value) in server.cfg but during launch it says `sv_gravity is now set to: "0.05999999866"`
Also this `Unable to set sv_maxgrenades: Value must be between 0 and 1`, IIRC Soldat always allowed for maximum 5 grenades

**Comment by BranDougherty** [comment]
I have local fixes for all these, I'll push them soon. I chose to go with changing the behavior, so the name makes sense. Like setting `sv_minimap "0"` will disable the minimap. Also, the `sv_gravity` thing is expected. The `GRAV` variable is a `Single`, which corresponds to an IEEE 754 single precision float. Due to the way the IEEE 754 encoding works, 0.06 can't be exactly represented, so it uses the closest value it can come up with. The code is accurately printing the actual floating point value used for gravity, it just doesn't exactly match what the user entered as a string. IMO this is the right behavior.

**Comment by BranDougherty** [comment]
I believe these are all fixed.
