### ISSUE TITLE
No default secondary weapon option in launcher

### ISSUE THREAD

**Issue by Ernshow** [opensoldat/opensoldat#165]
As in title - there is no option to select favorite secondary weapon from the launcher, so now it is always USSOCOM by default when joining new game.

PS. Do we place all the issues here, in "opensoldat" repo or to the specific ones (i.e. this one to "launcher")?

**Comment by BranDougherty** [comment]
Thanks for opening an issue. I'd say in general issues should be opened in the most relevant repository. If you're not sure where to open an issue, you can either ask in #opensoldat-dev in Discord or just default to opening it in this one, either is fine. In this case the game already has the `cl_player_secwep` cvar, which allows you to choose a default secondary, so the issue is missing UI in the launcher (tracking in opensoldat/launcher#14).
