### ISSUE TITLE
Specify server's country flag on configuration file.

### ISSUE THREAD

**Issue by IAmEnchant** [opensoldat/opensoldat#6]
In-game lobby, There're many servers with wrong country flag even if web lobby correct flag displayed it.
I think It is based on server's IP. but I wish I could specify it in a config file.
like this

`Server_Flag=KR`

And if this value is null, then the flag is based on server's IP. else, the flag is based on confg file.

Thanks to keep developing Soldat.

**Comment by jrgp** [comment]
Hey @IAmEnchant I just updated the Soldat lobby's ip2country database (it hadn't been updated for ~5 months due to maxmind changing their API) so now your server flag should be correct.

I'm curious for @helloer's thoughts here but I don't think we should let the server's flag be decided based on a config entry, as this would let people falsify where their servers are actually hosted

**Comment by Dankage102** [comment]
I would make the flag near server name to be specified in config file and add second one near server ip which would be chosen by api. Server can be hosted for example in France but playerbase speaks Polish and that way you know main language of the server if they specify the flag by themselves.

**Comment by BranDougherty** [comment]
Closed now that we are moving to a new lobby. I would say that having the flag/country column represent the location of the server is probably the more useful and relevant information to most players. Having 2 flags could be confusing visually. I'm more open to a general concept of "server language(s)", possibly implemented by convention in server description (think `[lang=PL]`, `[lang=FR]`, which can be filtered as text by launcher) if there is an actual demand for it.
