### ISSUE TITLE
Inconsistent managing of config files and assets

### ISSUE THREAD

**Issue by SwamiUmami** [opensoldat/opensoldat#82]
I'm reviewing how Soldat handles config files. Soldat's behaviour looks inconsistent:
- Client and server create folder structure on every run
- Client and server don't overwrite config files if they already exist
- Client copies `client.cfg` (and `taunts.cfg`, but this file was forgotten) to `configs` folder
- Server is a mess. It has many config files, but they are all treated differently:
  - Some files (`mapslist.txt`, `remote.txt`) are not present in `soldat.smod`, server doesn't try to create/extract them, but still tries to load configs from there
  - `bots` folder is present in `soldat.smod`, but it's not extracted to configs folder, so server can't find them
  - `server.cfg` works ok, it's extracted from `soldat.smod`
  - `weapons.ini` and `weapons_realistic.ini` are present in `soldat.smod`, but they are in wrong path (root of `soldat.smod` instead of `configs` folder). Server tries to extract them to `configs` folder
  - `banned.txt` and `bannedhw.txt` are not extracted, they are created as empty files if they are missing
- Client and server don't use PhysFS to read config files, so they won't be read from `soldat.smod`

Client also needs `play-regular.ttf` file, which is copied to `bin` folder by CMake. So, there are currently 2 approaches to distribution of game files (configs/assets):
- `play-regular.ttf` and `soldat.smod` are copied to `bin` folder (CMake feature)
- Configs are extracted from `soldat.smod` on first run

This inconsistency makes me wonder how other files will be included in a Soldat release. I think some other files like README, LICENSE, `changelog.txt`, Soldat's manual, ...) should be in zipped Soldat release. So, will Soldat unpack them from `soldat.smod`, or is it better to copy with CMake?

Wouldn't it be better if there was only 1 way to include game files?
**I propose**:
- Client and server don't need to create folders or extract/create config files
- When making a release of [base](https://github.com/Soldat/base), 3 archive files should be uploaded:
  - `soldat.smod`
  - `client.zip`: contains `play-regular.ttf` and `configs` folder
  - `server.zip`: contains `bots` and `configs` folders
- New archive files (`client.zip`, `server.zip`) should have all the folder structure
- CMake changes to download `client.zip` or `server.zip`, and extract to `bin` directory on `make`
- New GitHub workflow in [base](https://github.com/Soldat/base) for creating releases

**Benefits**
- When someone downloads game, he is welcomed with README, configs, and whole folder structure. Files are not extracted from `soldat.smod` on first run. This behaviour is more similar to 1.7.1
- Soldat's behavior becomes more consistent and structured, there is only 1 way to include game files
- Client and server code becomes shorter, and hopefully is less buggy (don't need to change Soldat code when [base](https://github.com/Soldat/base) changes)
- Client-only and server-only files become separated. Currently `soldat.smod` has configs for client and server, but client-only build needs only client files, and server-only build needs only server files

**Downsides**
- If user deletes config files, they will not be recreated from `soldat.smod`
- Affects Makefile and other build methods

**Alternatives**
Find another way to keep Soldat's behaviour consistent (config files, `play-regular.ttf`, README/license/manual). Maybe config files shouldn't be in base repository? Or maybe it's important to keep config files in `soldat.smod`, so that users can modify Soldat and create their own version of `soldat.smod` with custom configs?

I leave this open for discussion.

**Comment by BranDougherty** [comment]
Thank you for the detailed analysis. Your proposed solution makes sense. I'll make some time soon to think more about how the different files relate, and specifically about the mod creation workflow then made a decision on this.

**Comment by BranDougherty** [comment]
OK, I got around to this (sorry for the wait). I agree with your approach on almost all points. There will still be some amount of directory creating by Soldat, and synchronization between `Soldat/base` and `Soldat/soldat`. But this will decouple them to an extent. Having `client.zip` and `server.zip` to ship other accessory files will be useful as well.

Regenerating config files from `soldat.smod` is nice in theory, but realistically users are expected to modify those files. Once that happens, if they are deleted, I would say regenerating the default file is meager recompense. A descriptive error message might actually be more helpful in some cases.

I hope if anyone has a point they would like to raise they will comment on it. Otherwise I'll implement this in the next couple days.

**Comment by BranDougherty** [comment]
I backed out of this approach, and went back to just having everything in soldat.smod. I wound up reimplementing the unpacking behavior twice (once in CMake for development, once in shell for AppImages) trying to make this work. Very difficult to see that kind of stuff coming if you don't have a clear picture of all the steps you will need to take. I think the original method was the right way to go about it. In order to have the full folder structure presented to users, we should run the client+server once, so they unpack their files, as part of the release process.
